import { EventDifficulty } from '@prisma/client';

export type DemoHuntPlace = {
  id: string;
  title: string;
  description: string;
  latitude: number;
  longitude: number;
  orderIndex: number;
  hint: string;
  questionId: string;
  radiusMeters?: number;
};

export type DemoHunt = {
  id: string;
  title: string;
  description: string;
  city: string;
  /** Wikimedia Commons URL of a landmark place in this hunt (event card cover). */
  coverImage: string;
  difficulty: EventDifficulty;
  rewardPoints: number;
  places: DemoHuntPlace[];
};

/** Rotate through practice mật thư questions (001–034). */
function q(n: number): string {
  const id = ((n - 1) % 34) + 1;
  return `seed-practice-matthu-${String(id).padStart(3, '0')}`;
}

/**
 * 20 demo hunts across major Vietnamese cities.
 * Questions reuse seed-practice-matthu-* (COMMUNITY practice bank).
 */
export const demoHunts: DemoHunt[] = [
  {
    id: 'seed-event-hanoi',
    title: 'Mật thư phố cổ Hà Nội',
    description:
      'Đi bộ quanh Hồ Hoàn Kiếm, Văn Miếu và Cầu Long Biên — giải mật thư tại từng điểm.',
    city: 'Hà Nội',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Hanoi_-_Turtle_Tower_%28Th%C3%A1p_R%C3%B9a%29%2C_Ho%C3%A0n_Ki%E1%BA%BFm_Lake.jpg/1280px-Hanoi_-_Turtle_Tower_%28Th%C3%A1p_R%C3%B9a%29%2C_Ho%C3%A0n_Ki%E1%BA%BFm_Lake.jpg',
    difficulty: EventDifficulty.MEDIUM,
    rewardPoints: 250,
    places: [
      {
        id: 'seed-place-hanoi-hoan-kiem',
        title: 'Hồ Hoàn Kiếm',
        description: 'Hồ nước biểu tượng của Hà Nội, cạnh Tháp Rùa và cầu Thê Húc.',
        latitude: 21.028511,
        longitude: 105.852019,
        orderIndex: 0,
        hint: 'Đứng gần cầu Thê Húc nhìn ra Tháp Rùa.',
        questionId: 'seed-practice-matthu-003',
        radiusMeters: 120,
      },
      {
        id: 'seed-place-hanoi-van-mieu',
        title: 'Văn Miếu – Quốc Tử Giám',
        description: 'Trường đại học đầu tiên của Việt Nam.',
        latitude: 21.026661,
        longitude: 105.835558,
        orderIndex: 1,
        hint: 'Cổng chính Văn Miếu trên phố Quốc Tử Giám.',
        questionId: 'seed-practice-matthu-024',
        radiusMeters: 120,
      },
      {
        id: 'seed-place-hanoi-long-bien',
        title: 'Cầu Long Biên',
        description: 'Cầu sắt lịch sử bắc qua sông Hồng.',
        latitude: 21.043556,
        longitude: 105.847778,
        orderIndex: 2,
        hint: 'Đầu cầu phía Hoàn Kiếm, gần Trần Nhật Duật.',
        questionId: 'seed-practice-matthu-018',
        radiusMeters: 150,
      },
    ],
  },
  {
    id: 'seed-event-hcmc',
    title: 'Săn mật thư Sài Gòn',
    description:
      'Ba điểm Quận 1: Chợ Bến Thành, Nhà thờ Đức Bà và phố đi bộ Nguyễn Huệ.',
    city: 'TP. Hồ Chí Minh',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Ben_Thanh%2C_Ciudad_Ho_Chi_Minh%2C_Vietnam%2C_2013-08-14%2C_DD_01.JPG/1280px-Ben_Thanh%2C_Ciudad_Ho_Chi_Minh%2C_Vietnam%2C_2013-08-14%2C_DD_01.JPG',
    difficulty: EventDifficulty.HARD,
    rewardPoints: 400,
    places: [
      {
        id: 'seed-place-hcmc-ben-thanh',
        title: 'Chợ Bến Thành',
        description: 'Chợ trung tâm biểu tượng của Sài Gòn.',
        latitude: 10.772545,
        longitude: 106.698044,
        orderIndex: 0,
        hint: 'Cổng chính nhìn ra vòng xoay Quách Thị Trang.',
        questionId: 'seed-practice-matthu-012',
        radiusMeters: 120,
      },
      {
        id: 'seed-place-hcmc-duc-ba',
        title: 'Nhà thờ Đức Bà',
        description: 'Nhà thờ chính tòa Sài Gòn.',
        latitude: 10.779783,
        longitude: 106.699017,
        orderIndex: 1,
        hint: 'Công trường Công xã Paris, hai tháp chuông.',
        questionId: 'seed-practice-matthu-016',
        radiusMeters: 120,
      },
      {
        id: 'seed-place-hcmc-nguyen-hue',
        title: 'Phố đi bộ Nguyễn Huệ',
        description: 'Đại lộ đi bộ từ UBND TP đến sông Sài Gòn.',
        latitude: 10.773456,
        longitude: 106.703278,
        orderIndex: 2,
        hint: 'Giữa phố đi bộ, gần tượng đài Bác Hồ.',
        questionId: 'seed-practice-matthu-013',
        radiusMeters: 120,
      },
    ],
  },
  {
    id: 'seed-event-haiphong',
    title: 'Mật thư cảng Hải Phòng',
    description: 'Khám phá nhà hát lớn, vườn hoa và chợ Sắt — trung tâm thành phố cảng.',
    city: 'Hải Phòng',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/0/0f/03-OPERA_HOUSE.jpg',
    difficulty: EventDifficulty.MEDIUM,
    rewardPoints: 280,
    places: [
      {
        id: 'seed-place-hp-nha-hat',
        title: 'Nhà hát lớn Hải Phòng',
        description: 'Công trình kiến trúc Pháp giữa lòng thành phố.',
        latitude: 20.856956,
        longitude: 106.682206,
        orderIndex: 0,
        hint: 'Quảng trường Nhà hát, đường Trần Hưng Đạo.',
        questionId: q(1),
      },
      {
        id: 'seed-place-hp-vuon-hoa',
        title: 'Vườn hoa Nguyễn Du',
        description: 'Công viên trung tâm gần nhà hát.',
        latitude: 20.8558,
        longitude: 106.6835,
        orderIndex: 1,
        hint: 'Khu vườn hoa đối diện nhà hát lớn.',
        questionId: q(5),
      },
      {
        id: 'seed-place-hp-cho-sat',
        title: 'Chợ Sắt',
        description: 'Chợ lâu đời của Hải Phòng.',
        latitude: 20.8512,
        longitude: 106.6801,
        orderIndex: 2,
        hint: 'Gần cầu Xi Măng, khu chợ nhộn nhịp.',
        questionId: q(10),
      },
    ],
  },
  {
    id: 'seed-event-danang',
    title: 'Mật thư Đà Nẵng bên sông Hàn',
    description: 'Cầu Rồng, cầu tình yêu và Bà Nà phía xa — săn mật thư dọc bờ sông.',
    city: 'Đà Nẵng',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Da_Nang_-_Dragon_Bridge.jpg/1280px-Da_Nang_-_Dragon_Bridge.jpg',
    difficulty: EventDifficulty.MEDIUM,
    rewardPoints: 300,
    places: [
      {
        id: 'seed-place-dn-cau-rong',
        title: 'Cầu Rồng',
        description: 'Cầu biểu tượng phun lửa – nước của Đà Nẵng.',
        latitude: 16.061189,
        longitude: 108.227661,
        orderIndex: 0,
        hint: 'Đứng phía sông Hàn nhìn đầu rồng.',
        questionId: q(2),
      },
      {
        id: 'seed-place-dn-cau-tinh-yeu',
        title: 'Cầu tình yêu',
        description: 'Cầu đi bộ với hàng ổ khóa tình yêu.',
        latitude: 16.0605,
        longitude: 108.2248,
        orderIndex: 1,
        hint: 'Gần tượng Cá Chép hóa Rồng.',
        questionId: q(11),
      },
      {
        id: 'seed-place-dn-cho-han',
        title: 'Chợ Hàn',
        description: 'Chợ trung tâm Đà Nẵng bên sông.',
        latitude: 16.0682,
        longitude: 108.2235,
        orderIndex: 2,
        hint: 'Cổng chợ trên đường Hùng Vương.',
        questionId: q(9),
      },
    ],
  },
  {
    id: 'seed-event-cantho',
    title: 'Mật thư miền Tây Cần Thơ',
    description: 'Bến Ninh Kiều, chợ đêm và nhà cổ — hành trình mật thư sông nước.',
    city: 'Cần Thơ',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/B%E1%BA%BFn_Ninh_Ki%E1%BB%81u%2C_C%E1%BA%A7n_Th%C6%A1.JPG/1280px-B%E1%BA%BFn_Ninh_Ki%E1%BB%81u%2C_C%E1%BA%A7n_Th%C6%A1.JPG',
    difficulty: EventDifficulty.MEDIUM,
    rewardPoints: 280,
    places: [
      {
        id: 'seed-place-ct-ninh-kieu',
        title: 'Bến Ninh Kiều',
        description: 'Biểu tượng thành phố Cần Thơ bên sông Hậu.',
        latitude: 10.031389,
        longitude: 105.784722,
        orderIndex: 0,
        hint: 'Công viên bến tàu, nhìn ra sông.',
        questionId: 'seed-practice-matthu-021',
      },
      {
        id: 'seed-place-ct-cho-dem',
        title: 'Chợ đêm Ninh Kiều',
        description: 'Khu ẩm thực và mua sắm về đêm.',
        latitude: 10.0331,
        longitude: 105.7858,
        orderIndex: 1,
        hint: 'Dãy quán gần cầu đi bộ.',
        questionId: q(10),
      },
      {
        id: 'seed-place-ct-nha-co',
        title: 'Nhà cổ Bình Thủy',
        description: 'Ngôi nhà cổ nổi tiếng gần Cần Thơ.',
        latitude: 10.0792,
        longitude: 105.7356,
        orderIndex: 2,
        hint: 'Khu Bình Thủy, kiến trúc Pháp – Việt.',
        questionId: q(8),
        radiusMeters: 150,
      },
    ],
  },
  {
    id: 'seed-event-hue',
    title: 'Mật thư cố đô Huế',
    description: 'Ngọ Môn, cầu Trường Tiền và chợ Đông Ba — mật thư trong lòng cố đô.',
    city: 'Huế',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Hu%E1%BA%BF_%282024%29_-_Meridian_Gate_-_Ng%E1%BB%8D_M%C3%B4n_%28Ho%C3%A0ng_th%C3%A0nh_Hu%E1%BA%BF%29_-_img_02.jpg/1280px-Hu%E1%BA%BF_%282024%29_-_Meridian_Gate_-_Ng%E1%BB%8D_M%C3%B4n_%28Ho%C3%A0ng_th%C3%A0nh_Hu%E1%BA%BF%29_-_img_02.jpg',
    difficulty: EventDifficulty.HARD,
    rewardPoints: 350,
    places: [
      {
        id: 'seed-place-hue-ngo-mon',
        title: 'Ngọ Môn',
        description: 'Cổng chính Hoàng thành Huế.',
        latitude: 16.469722,
        longitude: 107.579167,
        orderIndex: 0,
        hint: 'Mặt tiền Hoàng thành nhìn ra đường Lê Huân.',
        questionId: q(14),
        radiusMeters: 150,
      },
      {
        id: 'seed-place-hue-truong-tien',
        title: 'Cầu Trường Tiền',
        description: 'Cầu sắt sáu nhịp biểu tượng Huế.',
        latitude: 16.4691,
        longitude: 107.5902,
        orderIndex: 1,
        hint: 'Giữa cầu, nhìn về phía sông Hương.',
        questionId: q(15),
      },
      {
        id: 'seed-place-hue-dong-ba',
        title: 'Chợ Đông Ba',
        description: 'Chợ lớn bên sông Hương.',
        latitude: 16.4708,
        longitude: 107.5865,
        orderIndex: 2,
        hint: 'Cổng chợ gần cầu Trường Tiền.',
        questionId: q(9),
      },
    ],
  },
  {
    id: 'seed-event-nhatrang',
    title: 'Mật thư vịnh Nha Trang',
    description: 'Tháp Bà, nhà thờ Đá và chợ Đầm — săn mật thư ven biển.',
    city: 'Nha Trang',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/04052023_Ponagar_Hindu_temples_complex%2C_Nha_Trang_Vietnam_-_152.jpg/1280px-04052023_Ponagar_Hindu_temples_complex%2C_Nha_Trang_Vietnam_-_152.jpg',
    difficulty: EventDifficulty.MEDIUM,
    rewardPoints: 300,
    places: [
      {
        id: 'seed-place-nt-thap-ba',
        title: 'Tháp Bà Ponagar',
        description: 'Tháp Chăm cổ trên đồi phía bắc Nha Trang.',
        latitude: 12.265278,
        longitude: 109.195556,
        orderIndex: 0,
        hint: 'Khu di tích Tháp Bà, đường 2/4.',
        questionId: q(3),
        radiusMeters: 150,
      },
      {
        id: 'seed-place-nt-nha-tho-da',
        title: 'Nhà thờ Đá Nha Trang',
        description: 'Nhà thờ núi với đá granit đặc trưng.',
        latitude: 12.2456,
        longitude: 109.1917,
        orderIndex: 1,
        hint: 'Trên đồi, nhìn xuống thành phố.',
        questionId: q(16),
      },
      {
        id: 'seed-place-nt-cho-dam',
        title: 'Chợ Đầm',
        description: 'Chợ trung tâm Nha Trang.',
        latitude: 12.2503,
        longitude: 109.1911,
        orderIndex: 2,
        hint: 'Gần cầu Trần Phú.',
        questionId: q(10),
      },
    ],
  },
  {
    id: 'seed-event-dalat',
    title: 'Mật thư thành phố ngàn hoa',
    description: 'Hồ Xuân Hương, chợ Đà Lạt và nhà thờ Con Gà — khí trời se lạnh, mật thư ấm áp.',
    city: 'Đà Lạt',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/a/ae/Da_Lat%2C_view_to_Xuan_Huong_lake_2.jpg',
    difficulty: EventDifficulty.MEDIUM,
    rewardPoints: 300,
    places: [
      {
        id: 'seed-place-dl-xuan-huong',
        title: 'Hồ Xuân Hương',
        description: 'Hồ trung tâm hình bán nguyệt của Đà Lạt.',
        latitude: 11.9404,
        longitude: 108.4383,
        orderIndex: 0,
        hint: 'Bờ hồ gần tượng đài.',
        questionId: 'seed-practice-matthu-034',
      },
      {
        id: 'seed-place-dl-cho',
        title: 'Chợ Đà Lạt',
        description: 'Chợ trung tâm đặc sản và hoa.',
        latitude: 11.9417,
        longitude: 108.4378,
        orderIndex: 1,
        hint: 'Khu chợ đêm / chợ chính.',
        questionId: q(10),
      },
      {
        id: 'seed-place-dl-con-ga',
        title: 'Nhà thờ Con Gà',
        description: 'Nhà thờ Chính tòa Đà Lạt với tượng gà trống.',
        latitude: 11.9439,
        longitude: 108.4371,
        orderIndex: 2,
        hint: 'Tháp chuông có tượng gà.',
        questionId: q(16),
      },
    ],
  },
  {
    id: 'seed-event-vungtau',
    title: 'Mật thư Vũng Tàu biển xanh',
    description: 'Tượng Chúa, Bạch Dinh và bãi Trước — mật thư giữa gió biển.',
    city: 'Vũng Tàu',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Statue_of_Jesus_in_Vung_Tau.jpg/1280px-Statue_of_Jesus_in_Vung_Tau.jpg',
    difficulty: EventDifficulty.EASY,
    rewardPoints: 250,
    places: [
      {
        id: 'seed-place-vt-tuong-chua',
        title: 'Tượng Chúa Kitô',
        description: 'Tượng Chúa dang tay trên núi Nhỏ.',
        latitude: 10.326389,
        longitude: 107.084722,
        orderIndex: 0,
        hint: 'Lên núi Nhỏ, nhìn ra biển Đông.',
        questionId: 'seed-practice-matthu-019',
        radiusMeters: 150,
      },
      {
        id: 'seed-place-vt-bach-dinh',
        title: 'Bạch Dinh',
        description: 'Dinh thự trắng thời Pháp trên đồi.',
        latitude: 10.3481,
        longitude: 107.0769,
        orderIndex: 1,
        hint: 'Đồi có dinh trắng nhìn bãi Trước.',
        questionId: q(14),
      },
      {
        id: 'seed-place-vt-bai-truoc',
        title: 'Bãi Trước',
        description: 'Bãi biển trung tâm thành phố.',
        latitude: 10.3417,
        longitude: 107.0775,
        orderIndex: 2,
        hint: 'Đường Quang Trung dọc bãi biển.',
        questionId: q(20),
      },
    ],
  },
  {
    id: 'seed-event-quynhon',
    title: 'Mật thư Quy Nhơn',
    description: 'Tháp Đôi, Quảng trường Nguyễn Tất Thành và biển Quy Nhơn.',
    city: 'Quy Nhơn',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/0040323_Thap_Doi_Cham_Hindu_complex%2C_Quy_Nhon%2C_Binh_Dinh_Vietnam_281.jpg/1280px-0040323_Thap_Doi_Cham_Hindu_complex%2C_Quy_Nhon%2C_Binh_Dinh_Vietnam_281.jpg',
    difficulty: EventDifficulty.MEDIUM,
    rewardPoints: 270,
    places: [
      {
        id: 'seed-place-qn-thap-doi',
        title: 'Tháp Đôi',
        description: 'Đôi tháp Chăm cổ trong thành phố.',
        latitude: 13.7764,
        longitude: 109.2147,
        orderIndex: 0,
        hint: 'Khu Tháp Đôi, đường Trần Hưng Đạo.',
        questionId: q(3),
      },
      {
        id: 'seed-place-qn-quang-truong',
        title: 'Quảng trường Nguyễn Tất Thành',
        description: 'Quảng trường ven biển trung tâm.',
        latitude: 13.7712,
        longitude: 109.2236,
        orderIndex: 1,
        hint: 'Gần tượng đài và bãi biển.',
        questionId: q(22),
      },
      {
        id: 'seed-place-qn-cho',
        title: 'Chợ Lớn Quy Nhơn',
        description: 'Chợ trung tâm thành phố.',
        latitude: 13.7756,
        longitude: 109.2194,
        orderIndex: 2,
        hint: 'Khu chợ đông đúc trung tâm.',
        questionId: q(9),
      },
    ],
  },
  {
    id: 'seed-event-buonmathuot',
    title: 'Mật thư cao nguyên Buôn Ma Thuột',
    description: 'Bảo tàng Thế giới Cà phê, hồ Ea Kao và trung tâm thành phố.',
    city: 'Buôn Ma Thuột',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Coffee_Trung_Nguyen_Legend.jpg/1280px-Coffee_Trung_Nguyen_Legend.jpg',
    difficulty: EventDifficulty.MEDIUM,
    rewardPoints: 280,
    places: [
      {
        id: 'seed-place-bmt-ca-phe',
        title: 'Bảo tàng Thế giới Cà phê',
        description: 'Không gian cà phê nổi tiếng của Buôn Ma Thuột.',
        latitude: 12.6797,
        longitude: 108.0378,
        orderIndex: 0,
        hint: 'Khu phức hợp Trung Nguyên Legend.',
        questionId: q(14),
        radiusMeters: 150,
      },
      {
        id: 'seed-place-bmt-cho',
        title: 'Chợ trung tâm Buôn Ma Thuột',
        description: 'Chợ chính của thành phố.',
        latitude: 12.6667,
        longitude: 108.05,
        orderIndex: 1,
        hint: 'Khu chợ đông gần trung tâm.',
        questionId: q(9),
      },
      {
        id: 'seed-place-bmt-tuong-dai',
        title: 'Quảng trường 10/3',
        description: 'Quảng trường trung tâm thành phố.',
        latitude: 12.6681,
        longitude: 108.0478,
        orderIndex: 2,
        hint: 'Gần trụ sở UBND thành phố.',
        questionId: q(25),
      },
    ],
  },
  {
    id: 'seed-event-thanhhoa',
    title: 'Mật thư xứ Thanh',
    description: 'Tượng đài Lê Lợi, cầu Hàm Rồng và trung tâm thành phố Thanh Hóa.',
    city: 'Thanh Hóa',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/a/a9/C%E1%BA%A7u_H%C3%A0m_R%E1%BB%93ng_%28cropped%29.jpg',
    difficulty: EventDifficulty.EASY,
    rewardPoints: 240,
    places: [
      {
        id: 'seed-place-th-le-loi',
        title: 'Tượng đài Lê Lợi',
        description: 'Biểu tượng trung tâm thành phố.',
        latitude: 19.8069,
        longitude: 105.7851,
        orderIndex: 0,
        hint: 'Quảng trường trung tâm.',
        questionId: q(23),
      },
      {
        id: 'seed-place-th-ham-rong',
        title: 'Cầu Hàm Rồng',
        description: 'Cầu lịch sử bắc sông Mã.',
        latitude: 19.8456,
        longitude: 105.8,
        orderIndex: 1,
        hint: 'Khu vực núi Hàm Rồng.',
        questionId: q(15),
        radiusMeters: 150,
      },
      {
        id: 'seed-place-th-cho',
        title: 'Chợ Vườn Hoa',
        description: 'Chợ trung tâm Thanh Hóa.',
        latitude: 19.8056,
        longitude: 105.7767,
        orderIndex: 2,
        hint: 'Khu chợ gần trung tâm.',
        questionId: q(10),
      },
    ],
  },
  {
    id: 'seed-event-vinh',
    title: 'Mật thư thành Vinh',
    description: 'Quảng trường Hồ Chí Minh, công viên Trung tâm và cầu Cửa Hội phía xa.',
    city: 'Vinh',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/4/43/Qu%E1%BA%A3ng_tr%C6%B0%E1%BB%9Dng_H%E1%BB%93_Ch%C3%AD_Minh.jpg',
    difficulty: EventDifficulty.MEDIUM,
    rewardPoints: 260,
    places: [
      {
        id: 'seed-place-vinh-quang-truong',
        title: 'Quảng trường Hồ Chí Minh',
        description: 'Quảng trường lớn trung tâm Vinh.',
        latitude: 18.6792,
        longitude: 105.6811,
        orderIndex: 0,
        hint: 'Tượng đài Bác Hồ giữa quảng trường.',
        questionId: q(22),
      },
      {
        id: 'seed-place-vinh-cong-vien',
        title: 'Công viên Trung tâm',
        description: 'Công viên xanh gần trung tâm thành phố.',
        latitude: 18.6764,
        longitude: 105.6831,
        orderIndex: 1,
        hint: 'Khu công viên gần quảng trường.',
        questionId: q(13),
      },
      {
        id: 'seed-place-vinh-cho',
        title: 'Chợ Vinh',
        description: 'Chợ lớn của thành phố.',
        latitude: 18.6728,
        longitude: 105.6867,
        orderIndex: 2,
        hint: 'Khu chợ trung tâm đông đúc.',
        questionId: q(9),
      },
    ],
  },
  {
    id: 'seed-event-halong',
    title: 'Mật thư Hạ Long',
    description: 'Bảo tàng Quảng Ninh, Sun World và bãi Cháy — mật thư bên vịnh.',
    city: 'Hạ Long',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/7/79/Ha_Long_Bay_in_2019.jpg',
    difficulty: EventDifficulty.HARD,
    rewardPoints: 350,
    places: [
      {
        id: 'seed-place-hl-bao-tang',
        title: 'Bảo tàng Quảng Ninh',
        description: 'Bảo tàng hình chong chóng nổi tiếng.',
        latitude: 20.9525,
        longitude: 107.0531,
        orderIndex: 0,
        hint: 'Công trình trắng cạnh vịnh.',
        questionId: q(14),
        radiusMeters: 150,
      },
      {
        id: 'seed-place-hl-bai-chay',
        title: 'Bãi Cháy',
        description: 'Khu du lịch biển trung tâm Hạ Long.',
        latitude: 20.9608,
        longitude: 107.0431,
        orderIndex: 1,
        hint: 'Đường bao biển Bãi Cháy.',
        questionId: q(20),
      },
      {
        id: 'seed-place-hl-cong-vien',
        title: 'Công viên Sun World Hạ Long',
        description: 'Khu vui chơi phía Bãi Cháy (cổng khu vực).',
        latitude: 20.9619,
        longitude: 107.0389,
        orderIndex: 2,
        hint: 'Gần cáp treo / cổng Sun World.',
        questionId: q(13),
        radiusMeters: 150,
      },
    ],
  },
  {
    id: 'seed-event-bienhoa',
    title: 'Mật thư Biên Hòa',
    description: 'Công viên Biên Hùng, chùa Ông và cầu Ghềnh lịch sử.',
    city: 'Biên Hòa',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Bien_Hung_Park_%2849356307813%29.jpg/1280px-Bien_Hung_Park_%2849356307813%29.jpg',
    difficulty: EventDifficulty.EASY,
    rewardPoints: 240,
    places: [
      {
        id: 'seed-place-bh-bien-hung',
        title: 'Công viên Biên Hùng',
        description: 'Công viên lớn trung tâm Biên Hòa.',
        latitude: 10.9578,
        longitude: 106.8425,
        orderIndex: 0,
        hint: 'Khu công viên xanh trung tâm.',
        questionId: q(13),
      },
      {
        id: 'seed-place-bh-chua-ong',
        title: 'Chùa Ông',
        description: 'Ngôi chùa cổ bên sông Đồng Nai.',
        latitude: 10.9525,
        longitude: 106.8256,
        orderIndex: 1,
        hint: 'Gần bến đò / sông Đồng Nai.',
        questionId: q(16),
      },
      {
        id: 'seed-place-bh-cau-ghenh',
        title: 'Cầu Ghềnh',
        description: 'Cầu đường sắt lịch sử (khu vực di tích).',
        latitude: 10.9489,
        longitude: 106.8306,
        orderIndex: 2,
        hint: 'Khu vực cầu qua sông Đồng Nai.',
        questionId: q(15),
        radiusMeters: 150,
      },
    ],
  },
  {
    id: 'seed-event-thudaumot',
    title: 'Mật thư Thủ Dầu Một',
    description: 'Chùa Hội Khánh, bảo tàng Bình Dương và trung tâm thành phố.',
    city: 'Thủ Dầu Một',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Hoi_Khanh_Pagoda_in_Binh_Duong.jpg/1280px-Hoi_Khanh_Pagoda_in_Binh_Duong.jpg',
    difficulty: EventDifficulty.EASY,
    rewardPoints: 240,
    places: [
      {
        id: 'seed-place-tdm-hoi-khanh',
        title: 'Chùa Hội Khánh',
        description: 'Ngôi chùa cổ nổi tiếng Bình Dương.',
        latitude: 10.9806,
        longitude: 106.6517,
        orderIndex: 0,
        hint: 'Chùa trên đường Cách Mạng Tháng Tám.',
        questionId: q(16),
      },
      {
        id: 'seed-place-tdm-bao-tang',
        title: 'Bảo tàng tỉnh Bình Dương',
        description: 'Bảo tàng giới thiệu lịch sử địa phương.',
        latitude: 10.9789,
        longitude: 106.6556,
        orderIndex: 1,
        hint: 'Gần trung tâm hành chính.',
        questionId: q(14),
      },
      {
        id: 'seed-place-tdm-cho',
        title: 'Chợ Thủ Dầu Một',
        description: 'Chợ trung tâm thành phố.',
        latitude: 10.9822,
        longitude: 106.6542,
        orderIndex: 2,
        hint: 'Khu chợ đông đúc trung tâm.',
        questionId: q(9),
      },
    ],
  },
  {
    id: 'seed-event-mytho',
    title: 'Mật thư Mỹ Tho',
    description: 'Bến tàu du lịch, chùa Vĩnh Tràng và trung tâm thành phố sông Tiền.',
    city: 'Mỹ Tho',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/VINH_TRANG.JPG/1280px-VINH_TRANG.JPG',
    difficulty: EventDifficulty.MEDIUM,
    rewardPoints: 260,
    places: [
      {
        id: 'seed-place-mt-ben-tau',
        title: 'Bến tàu du lịch Mỹ Tho',
        description: 'Điểm xuất phát tham quan cồn và sông Tiền.',
        latitude: 10.3542,
        longitude: 106.35,
        orderIndex: 0,
        hint: 'Bến tàu gần trung tâm, nhìn ra sông.',
        questionId: q(2),
      },
      {
        id: 'seed-place-mt-vinh-trang',
        title: 'Chùa Vĩnh Tràng',
        description: 'Ngôi chùa nổi tiếng kiến trúc Á – Âu.',
        latitude: 10.3619,
        longitude: 106.3331,
        orderIndex: 1,
        hint: 'Khu chùa lớn ngoài trung tâm một chút.',
        questionId: q(16),
        radiusMeters: 150,
      },
      {
        id: 'seed-place-mt-cho',
        title: 'Chợ Mỹ Tho',
        description: 'Chợ trung tâm thành phố.',
        latitude: 10.3567,
        longitude: 106.3611,
        orderIndex: 2,
        hint: 'Khu chợ gần trung tâm.',
        questionId: q(10),
      },
    ],
  },
  {
    id: 'seed-event-longxuyen',
    title: 'Mật thư Long Xuyên',
    description: 'Tượng đài Thoại Ngọc Hầu, chợ Long Xuyên và công viên ven sông.',
    city: 'Long Xuyên',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Ch%E1%BB%A3_th%C3%A0nh_ph%E1%BB%91_Long_Xuy%C3%AAn.jpg/1280px-Ch%E1%BB%A3_th%C3%A0nh_ph%E1%BB%91_Long_Xuy%C3%AAn.jpg',
    difficulty: EventDifficulty.EASY,
    rewardPoints: 230,
    places: [
      {
        id: 'seed-place-lx-tuong-dai',
        title: 'Tượng đài Thoại Ngọc Hầu',
        description: 'Biểu tượng trung tâm Long Xuyên.',
        latitude: 10.3864,
        longitude: 105.4352,
        orderIndex: 0,
        hint: 'Quảng trường trung tâm thành phố.',
        questionId: q(23),
      },
      {
        id: 'seed-place-lx-cho',
        title: 'Chợ Long Xuyên',
        description: 'Chợ lớn miền Tây.',
        latitude: 10.3839,
        longitude: 105.4381,
        orderIndex: 1,
        hint: 'Khu chợ đông gần sông.',
        questionId: q(9),
      },
      {
        id: 'seed-place-lx-cong-vien',
        title: 'Công viên Mỹ Phước',
        description: 'Công viên ven sông trung tâm.',
        latitude: 10.3889,
        longitude: 105.4339,
        orderIndex: 2,
        hint: 'Khu công viên xanh gần trung tâm.',
        questionId: q(13),
      },
    ],
  },
  {
    id: 'seed-event-pleiku',
    title: 'Mật thư cao nguyên Pleiku',
    description: 'Biển Hồ, nhà thờ gỗ và trung tâm thành phố núi.',
    city: 'Pleiku',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Bi%E1%BB%83n_H%E1%BB%93%2C_TP_Pleiku%2C_Gia_Lai.jpg/1280px-Bi%E1%BB%83n_H%E1%BB%93%2C_TP_Pleiku%2C_Gia_Lai.jpg',
    difficulty: EventDifficulty.MEDIUM,
    rewardPoints: 270,
    places: [
      {
        id: 'seed-place-pl-bien-ho',
        title: 'Biển Hồ (T\'Nưng)',
        description: 'Hồ núi lửa nổi tiếng gần Pleiku.',
        latitude: 14.0486,
        longitude: 107.9831,
        orderIndex: 0,
        hint: 'Khu du lịch Biển Hồ phía bắc thành phố.',
        questionId: q(33),
        radiusMeters: 200,
      },
      {
        id: 'seed-place-pl-nha-tho',
        title: 'Nhà thờ chính tòa Pleiku',
        description: 'Nhà thờ lớn tại trung tâm thành phố.',
        latitude: 13.9839,
        longitude: 108.0017,
        orderIndex: 1,
        hint: 'Nhà thờ gần khu trung tâm.',
        questionId: q(16),
        radiusMeters: 150,
      },
      {
        id: 'seed-place-pl-cho',
        title: 'Chợ trung tâm Pleiku',
        description: 'Chợ chính của thành phố.',
        latitude: 13.9833,
        longitude: 108.0,
        orderIndex: 2,
        hint: 'Khu chợ đông trung tâm.',
        questionId: q(9),
      },
    ],
  },
  {
    id: 'seed-event-phanthiet',
    title: 'Mật thư Phan Thiết',
    description: 'Tháp Po Sah Inư, đồi Dương Cơ và trung tâm thành phố biển.',
    city: 'Phan Thiết',
    coverImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Thap_Po_Sah_Inu_temple_Vietnam%2C_entrance_with_a_Cham_pilgrim_%2825716485038%29.jpg/1280px-Thap_Po_Sah_Inu_temple_Vietnam%2C_entrance_with_a_Cham_pilgrim_%2825716485038%29.jpg',
    difficulty: EventDifficulty.MEDIUM,
    rewardPoints: 280,
    places: [
      {
        id: 'seed-place-pt-thap-cham',
        title: 'Tháp Po Sah Inư',
        description: 'Tháp Chăm cổ gần Phan Thiết.',
        latitude: 10.9278,
        longitude: 108.1,
        orderIndex: 0,
        hint: 'Khu tháp trên đồi phía đông thành phố.',
        questionId: q(3),
        radiusMeters: 150,
      },
      {
        id: 'seed-place-pt-doi-duong',
        title: 'Đồi Dương Cơ',
        description: 'Đồi nhìn ra biển trung tâm Phan Thiết.',
        latitude: 10.9331,
        longitude: 108.1089,
        orderIndex: 1,
        hint: 'Khu vực đồi gần bãi biển.',
        questionId: q(20),
      },
      {
        id: 'seed-place-pt-cho',
        title: 'Chợ Phan Thiết',
        description: 'Chợ trung tâm thành phố.',
        latitude: 10.9289,
        longitude: 108.1022,
        orderIndex: 2,
        hint: 'Khu chợ trung tâm đông đúc.',
        questionId: q(10),
      },
    ],
  },
];
